# Generated by Django 5.2 on 2025-04-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_sale_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อหมวดหมู่')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='sales_app.category', verbose_name='หมวดหมู่หลัก')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้าทั้งหมด',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='รหัสสินค้า')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sales_app.category', verbose_name='สินค้า')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateField(verbose_name='วันที่เสนอราคา')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงินรวม')),
                ('status', models.CharField(choices=[('draft', 'แบบร่าง'), ('sent', 'ส่งแล้ว'), ('revised', 'ปรับแก้ไข'), ('approved', 'ลูกค้าอนุมัติ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('converted', 'แปลงเป็นใบแจ้งหนี้')], default='draft', max_length=10, verbose_name='รออนุมัติ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='sales_app.customer')),
            ],
            options={
                'verbose_name': 'ใบเสนอราคา',
                'verbose_name_plural': 'ใบเสนอราคาทั้งหมด',
                'db_table': 'quotation',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('draft', 'แบบร่าง'), ('sent', 'ส่งแล้ว'), ('partial', 'ชำระบางส่วน'), ('paid', 'ชำระแล้วทั้งหมด'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก'), ('pending', 'รอดำเนินการ')], default='pending', max_length=50, verbose_name='รอดำเนินการ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.customer')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.quotation')),
            ],
            options={
                'verbose_name': 'ใบแจ้งหนี้',
                'verbose_name_plural': 'ใบแจ้งหนี้ทั้งหมด',
                'db_table': 'invoice',
            },
        ),
    ]
