# Generated by Django 5.2 on 2025-04-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_remove_customer_contact_info_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashsale',
            options={'verbose_name': 'การขายเงินสด', 'verbose_name_plural': 'Cash Sales'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'ใบแจ้งหนี้', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'ใบเสนอราคา', 'verbose_name_plural': 'quotations'},
        ),
        migrations.AlterModelTable(
            name='cashsale',
            table='cash_sale',
        ),
    ]
