# Generated by Django 5.2 on 2025-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_alter_cashsale_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'หมวดหมู่สินค้า', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='customer',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='viber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viber ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='viber_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์ Viber'),
        ),
    ]
