# Generated by Django 5.2 on 2025-04-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_alter_category_options_customer_line_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'ลูกค้า', 'verbose_name_plural': 'customers'},
        ),
    ]
