# Generated by Django 5.2 on 2025-04-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='sales_app.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_app.quotation')),
            ],
            options={
                'db_table': 'quotation_item',
                'unique_together': {('quotation', 'product')},
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='Products',
            field=models.ManyToManyField(related_name='quotations', through='sales_app.QuotationItem', to='sales_app.product', verbose_name='สินค้าในใบเสนอราคา'),
        ),
    ]
