# Generated by Django 5.2 on 2025-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0006_quotationitem_quotation_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Products',
            field=models.ManyToManyField(related_name='QuotationItem', through='sales_app.QuotationItem', to='sales_app.product', verbose_name='สินค้าในใบเสนอราคา'),
        ),
    ]
