# Generated by Django 5.2 on 2025-04-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0008_alter_product_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
