# Generated by Django 5.2 on 2025-04-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0009_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='Products',
        ),
    ]
