# Generated by Django 5.2 on 2025-04-22 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0010_remove_quotation_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'โอน')], max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.invoice')),
            ],
            options={
                'verbose_name': 'ใบเสร็จรับเงิน',
                'verbose_name_plural': 'Receipts',
                'db_table': 'receipt',
            },
        ),
    ]
