# Generated by Django 5.2 on 2025-04-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0012_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_app.cashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sale_items', to='sales_app.product')),
            ],
            options={
                'db_table': 'cash_sale_item',
                'unique_together': {('cash_sale', 'product')},
            },
        ),
    ]
