# Generated by Django 5.2 on 2025-04-23 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0013_cashsaleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
