# Generated by Django 5.2 on 2025-04-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0014_alter_quotationitem_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashsaleitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cashsaleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='sales_app.category', verbose_name='หมวดหมู่ย่อย'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sales_app.invoice'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='sales_app.quotation'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='cashsaleitem',
            constraint=models.UniqueConstraint(fields=('cash_sale', 'product'), name='unique_cash_sale_product'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.UniqueConstraint(fields=('quotation', 'product'), name='unique_quotation_product'),
        ),
        migrations.AlterModelTable(
            name='invoiceitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table=None,
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='subtotal',
        ),
    ]
