# Generated by Django 5.2 on 2025-04-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0015_alter_cashsaleitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
