# Generated by Django 5.2 on 2025-04-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0016_rename_phone_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotationitem',
            name='unique_quotation_product',
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together={('quotation', 'product')},
        ),
    ]
