# Generated by Django 5.2 on 2025-04-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0018_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_app.invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'product')},
        ),
    ]
