# Generated by Django 5.2 on 2025-04-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0020_receipt_customer_alter_receipt_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('draft', 'แบบร่าง'), ('sent', 'ส่งแล้ว'), ('partial', 'ชำระบางส่วน'), ('paid', 'ชำระแล้วทั้งหมด'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก'), ('pending', 'รอดำเนินการ')], default='draft', max_length=50, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotations', to='sales_app.customer'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'รออนุมัติ'), ('sent', 'ส่งแล้ว'), ('revised', 'ปรับแก้ไข'), ('approved', 'ลูกค้าอนุมัติ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('converted', 'แปลงเป็นใบแจ้งหนี้')], default='draft', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='จำนวนเงินรวม'),
        ),
        migrations.AlterModelTable(
            name='quotation',
            table=None,
        ),
    ]
