# Generated by Django 5.2 on 2025-04-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0021_alter_invoice_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sales', to='sales_app.customer'),
        ),
    ]
